project_id = "nbrehbwfsmedbelzntqs"

[functions.check-identity-verification]
verify_jwt = false

[functions.create-identity-verification]
verify_jwt = false

[functions.check-stripe-connect]
verify_jwt = false

[functions.create-stripe-connect]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-booking-notification]
verify_jwt = false

[functions.send-stripe-onboarding-reminder]
verify_jwt = false

[functions.suggest-pricing]
verify_jwt = false
