project_id = "nbrehbwfsmedbelzntqs"

[functions.check-identity-verification]
verify_jwt = false

[functions.create-identity-verification]
verify_jwt = false

[functions.check-stripe-connect]
verify_jwt = false

[functions.create-stripe-connect]
verify_jwt = false

[functions.send-booking-notification]
verify_jwt = false
